name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install clasp
        run: npm install -g @google/clasp
      
      - name: Deploy Sheets Add-on
        run: |
          cd apps/sheets-addon
          clasp push
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
  
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Web Apps
        run: echo "Deploy web applications"