# مصفوفة النشر - Deployment Matrix
# تحدد متى يُسمح لمساعد بالرفع حسب نوع التغيير

version: "1.0"
last_updated: "2024-01-15"

# قواعد النشر العامة
global_rules:
  require_human_review: true
  max_concurrent_deployments: 2
  deployment_window: "09:00-17:00"
  emergency_override: true

# مصفوفة الأذونات
deployment_matrix:
  
  # مساعد Copilot
  copilot:
    allowed_changes:
      - ui
      - frontend
      - test
      - docs
    
    restrictions:
      ui:
        conditions:
          - backend_stable: true
          - no_breaking_changes: true
        dependencies:
          - check: "ai_models_compatible"
            action: "block_if_false"
      
      frontend:
        conditions:
          - api_version_match: true
          - css_conflicts_resolved: true
        dependencies:
          - check: "backend_endpoints_available"
            action: "warn_if_false"
      
      test:
        conditions:
          - existing_tests_pass: true
        dependencies: []
      
      docs:
        conditions: []
        dependencies: []
    
    blocked_changes:
      - ai
      - config
      - critical
    
    auto_deploy: false
    require_approval: true

  # مساعد Gemini  
  gemini:
    allowed_changes:
      - ai
      - agents
      - analysis
      - docs
    
    restrictions:
      ai:
        conditions:
          - ui_compatible: true
          - memory_usage_acceptable: true
          - api_rate_limits_ok: true
        dependencies:
          - check: "ui_components_stable"
            action: "block_if_false"
          - check: "database_schema_compatible"
            action: "warn_if_false"
      
      agents:
        conditions:
          - agent_conflicts_resolved: true
          - resource_limits_ok: true
        dependencies:
          - check: "other_agents_stable"
            action: "block_if_false"
      
      analysis:
        conditions:
          - data_sources_available: true
        dependencies:
          - check: "sheets_api_accessible"
            action: "block_if_false"
    
    blocked_changes:
      - ui
      - critical
      - config
    
    auto_deploy: true
    require_approval: false

  # المطور البشري
  human:
    allowed_changes:
      - critical
      - config
      - architecture
      - security
      - ui
      - ai
      - docs
    
    restrictions:
      critical:
        conditions:
          - backup_created: true
          - rollback_plan_ready: true
        dependencies:
          - check: "all_systems_healthy"
            action: "block_if_false"
      
      config:
        conditions:
          - config_validated: true
          - dependent_services_notified: true
        dependencies:
          - check: "no_active_deployments"
            action: "block_if_false"
      
      architecture:
        conditions:
          - impact_analysis_complete: true
          - migration_plan_ready: true
        dependencies:
          - check: "all_assistants_idle"
            action: "warn_if_false"
    
    blocked_changes: []
    auto_deploy: false
    require_approval: false

# شروط التوافق
compatibility_checks:
  
  ui_components_stable:
    description: "فحص استقرار مكونات الواجهة"
    command: "npm run test:ui"
    timeout: 60
    retry_count: 2
  
  ai_models_compatible:
    description: "فحص توافق نماذج الذكاء الاصطناعي"
    command: "node scripts/check_ai_compatibility.js"
    timeout: 120
    retry_count: 1
  
  backend_endpoints_available:
    description: "فحص توفر نقاط النهاية"
    command: "curl -f http://localhost:8080/health"
    timeout: 30
    retry_count: 3
  
  database_schema_compatible:
    description: "فحص توافق قاعدة البيانات"
    command: "node scripts/check_db_schema.js"
    timeout: 45
    retry_count: 1
  
  sheets_api_accessible:
    description: "فحص إمكانية الوصول لـ Google Sheets"
    command: "node scripts/test_sheets_connection.js"
    timeout: 30
    retry_count: 2
  
  all_systems_healthy:
    description: "فحص صحة جميع الأنظمة"
    command: "npm run health:full"
    timeout: 180
    retry_count: 1

# قواعد التضارب
conflict_resolution:
  
  # تضارب بين UI و AI
  ui_ai_conflict:
    priority: "human"
    action: "block_lower_priority"
    notification: "slack"
    message: "تضارب بين تحديثات الواجهة والذكاء الاصطناعي"
  
  # تضارب في الملفات الحرجة
  critical_files_conflict:
    priority: "human"
    action: "block_all"
    notification: "emergency"
    message: "تضارب في الملفات الحرجة - مراجعة فورية مطلوبة"
  
  # تضارب في الإعدادات
  config_conflict:
    priority: "human"
    action: "queue_changes"
    notification: "slack"
    message: "تضارب في الإعدادات - سيتم تطبيق التغييرات بالتسلسل"

# أوقات النشر المسموحة
deployment_windows:
  
  normal:
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
    hours: "09:00-17:00"
    timezone: "Asia/Riyadh"
  
  maintenance:
    days: ["saturday"]
    hours: "02:00-06:00"
    timezone: "Asia/Riyadh"
    allowed_changes: ["critical", "config", "security"]
  
  emergency:
    days: ["all"]
    hours: "all"
    conditions:
      - severity: "critical"
      - human_approval: true

# إعدادات الإشعارات
notifications:
  
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      deployment: "#deployments"
      alerts: "#alerts"
      general: "#general"
  
  discord:
    webhook_url: "${DISCORD_WEBHOOK_URL}"
    channels:
      deployment: "deployments"
      alerts: "alerts"
  
  email:
    smtp_server: "${SMTP_SERVER}"
    recipients:
      critical: ["admin@example.com"]
      deployment: ["team@example.com"]

# قوالب الرسائل
message_templates:
  
  deployment_blocked:
    title: "🚫 نشر محظور"
    body: |
      المساعد: {assistant}
      نوع التغيير: {change_type}
      السبب: {reason}
      الإجراء المطلوب: {required_action}
  
  deployment_approved:
    title: "✅ نشر معتمد"
    body: |
      المساعد: {assistant}
      نوع التغيير: {change_type}
      الملفات: {files_count}
      الوقت المتوقع: {estimated_time}
  
  conflict_detected:
    title: "⚠️ تضارب مكتشف"
    body: |
      نوع التضارب: {conflict_type}
      المساعدين المتأثرين: {affected_assistants}
      الملفات المتضاربة: {conflicting_files}
      الإجراء: {resolution_action}

# إعدادات المراقبة
monitoring:
  
  health_checks:
    interval: 30 # ثانية
    timeout: 10 # ثانية
    endpoints:
      - "/health"
      - "/api/status"
      - "/metrics"
  
  performance_thresholds:
    response_time: 500 # ms
    memory_usage: 80 # %
    cpu_usage: 70 # %
    error_rate: 1 # %
  
  alerts:
    escalation_time: 300 # ثانية
    max_retries: 3
    cooldown_period: 600 # ثانية