# نشر إنتاجي متقدم لـ AzizSys
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azizsys-production
  labels:
    app: azizsys
    version: v4.0
    tier: production
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: azizsys
      tier: production
  template:
    metadata:
      labels:
        app: azizsys
        tier: production
        version: v4.0
    spec:
      containers:
      - name: azizsys-main
        image: gcr.io/azizsys-project/azizsys:v4.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: websocket
        env:
        - name: NODE_ENV
          value: "production"
        - name: MULTILINGUAL_ENABLED
          value: "true"
        - name: ANALYTICS_ENABLED
          value: "true"
        - name: CONTEXT_MANAGER_ENABLED
          value: "true"
        - name: REDIS_HOST
          value: "redis-cluster"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: azizsys-config

---
apiVersion: v1
kind: Service
metadata:
  name: azizsys-service
  labels:
    app: azizsys
spec:
  selector:
    app: azizsys
    tier: production
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: websocket
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: azizsys-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azizsys-production
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azizsys-config
data:
  app.yaml: |
    server:
      port: 8080
      websocket_port: 8081
    
    features:
      multilingual: true
      analytics: true
      context_manager: true
      advanced_ai: true
    
    languages:
      supported: ["ar", "en", "fr", "es", "de", "ru", "zh", "ja", "pt", "tr"]
      default: "ar"
    
    analytics:
      retention_days: 30
      cleanup_interval: "0 2 * * *"
    
    performance:
      max_context_age: 3600000
      max_conversation_history: 10
      response_timeout: 30000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azizsys-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - api.azizsys.com
    secretName: azizsys-tls
  rules:
  - host: api.azizsys.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: azizsys-service
            port:
              number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  url: <base64-encoded-database-url>

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: azizsys-pdb
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: azizsys
      tier: production